services:
  postgres:
    container_name: pwn3_db
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - psql_socket:/var/run/postgresql
      - pwn3_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - pwn3_net

  master:
    container_name: pwn3_master
    build:
      context: ./master
    image: pwn3_master
    hostname: master.pwn3
    ports:
      - "${MASTER_HOST_PORT:-3333}:3333"
    volumes:
      - psql_socket:/var/run/postgresql
      - ./master/MasterServer:/opt/pwn3
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      pwn3_net:
        aliases:
          - master.pwn3

  game:
    container_name: pwn3_game
    build:
      context: ./game
    image: pwn3_game
    hostname: game.pwn3
    ports:
      - "${GAME_HOST_PORTS:-3000-3010}:3000-3010"
    volumes:
      - ./game/server.ini:/opt/pwn3/PwnAdventure3/Content/Server/server.ini
      - ./game/server.crt:/opt/pwn3/PwnAdventure3/Content/Server/server.crt
    depends_on:
      master:
        condition: service_started
    restart: unless-stopped
    networks:
      pwn3_net:
        aliases:
          - game.pwn3

networks:
  pwn3_net:

volumes:
  psql_socket:
    driver_opts:
      type: tmpfs
      device: tmpfs

  pwn3_db:
    driver: local
